# Generated by Django 4.1.1 on 2022-12-28 14:20

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import dropzone.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(unique=True)),
                ('total_size', models.IntegerField()),
                ('total_chunks', models.IntegerField()),
                ('chunk_size', models.IntegerField()),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to=dropzone.models.Session.session_upload_path)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChunkedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('file', models.FileField(upload_to=dropzone.models.ChunkedFile.chunk_upload_path)),
                ('index', models.IntegerField(db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', related_query_name='chunk', to='dropzone.session')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
