# Generated by Django 4.1.1 on 2022-12-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropzone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='file_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
